"""fix error in task model

Revision ID: 6cbecea307ef
Revises: 3db138a7f276
Create Date: 2024-11-29 14:56:39.874185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbecea307ef'
down_revision: Union[str, None] = '3db138a7f276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'created_by_user_id')
    # ### end Alembic commands ###
